version: "3.8"
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DBNAME=jamesweb
            - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
